services:
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command:
    - --tty=/dev/tty7
    device_cgroup_rules:
    - c 4:* rmw
    - c 13:* rmw
    - c 226:* rmw
    - c 199:* rmw
    environment:
    - ACCEPT_FSL_EULA=1
    image: torizon/weston-vivante@sha256:20b09290a5238b2b61d5f6965e2407347867100f488ce77cfd19f485d82501e6
    network_mode: host
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
version: '3'
